name: testss

channels:
  - conda-forge
  - defaults
  
dependencies:
 - python=3.6
 - pip
 - pip:
      - matplotlib
      - joblib
      - pathlib
      - keras
      - dlib
      - numpy
      - scipy
      - opencv
      - face_recognition
      - pandas
      - joblib
      - matplotlib
      - seaborn
      - plotly
      - PIL
      - pillow
      - os
      - cv2 
      - skimage
