channels:
 - conda-forge
dependencies:
 - python=3.7
 - pip:
      - matplotlib
      - joblib
      - pathlib
      - keras
      - dlib
      - numpy
      - scipy
      - opencv
      - face_recognition
      - pandas
      - joblib
      - matplotlib
      - seaborn
      - plotly
      - PIL
      - pillow
      - os
      - cv2 
      - skimage

