channels:
  - conda-forge
  - defaults
  
dependencies:
 - python=3.7
 - pip
 - pip:
      - matplotlib
      - joblib
      - pathlib
      - keras
      - dlib
      - numpy
      - scipy
      - opencv-python
      - face_recognition
      - pandas
      - joblib
      - matplotlib
      - seaborn
      - plotly
      - Pillow
      - cv2 
      - skimage
